(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var t=ba(this);function u(a,b){if(b)a:{var c=t;a=a.split(".");for(var d=0;d<a.length-1;d++){var h=a[d];if(!(h in c))break a;c=c[h]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(l){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(l||"")+"_"+h++,l)}function c(l,f){this.g=l;p(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",h=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=t[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function v(a){return a.raw=a}function w(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},x;
if("function"==typeof Object.setPrototypeOf)x=Object.setPrototypeOf;else{var y;a:{var ea={a:!0},fa={};try{fa.__proto__=ea;y=fa.a;break a}catch(a){}y=!1}x=y?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=x;
function z(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.aa=b.prototype}function ia(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(f){this.h=0;this.i=void 0;this.g=[];this.C=!1;var e=this.m();try{f(e.resolve,e.reject)}catch(g){e.reject(g)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(e){e(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var e=this;this.i(function(){e.s()})}this.g.push(f)};var h=t.setTimeout;c.prototype.i=function(f){h(f,0)};c.prototype.s=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var e=0;e<f.length;++e){var g=
f[e];f[e]=null;try{g()}catch(k){this.m(k)}}}this.g=null};c.prototype.m=function(f){this.i(function(){throw f;})};b.prototype.m=function(){function f(k){return function(m){g||(g=!0,k.call(e,m))}}var e=this,g=!1;return{resolve:f(this.P),reject:f(this.s)}};b.prototype.P=function(f){if(f===this)this.s(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.S(f);else{a:switch(typeof f){case "object":var e=null!=f;break a;case "function":e=!0;break a;default:e=!1}e?this.O(f):this.B(f)}};
b.prototype.O=function(f){var e=void 0;try{e=f.then}catch(g){this.s(g);return}"function"==typeof e?this.T(e,f):this.B(f)};b.prototype.s=function(f){this.L(2,f)};b.prototype.B=function(f){this.L(1,f)};b.prototype.L=function(f,e){if(0!=this.h)throw Error("Cannot settle("+f+", "+e+"): Promise already settled in state"+this.h);this.h=f;this.i=e;2===this.h&&this.R();this.X()};b.prototype.R=function(){var f=this;h(function(){if(f.Y()){var e=t.console;"undefined"!==typeof e&&e.error(f.i)}},1)};b.prototype.Y=
function(){if(this.C)return!1;var f=t.CustomEvent,e=t.Event,g=t.dispatchEvent;if("undefined"===typeof g)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof e?f=new e("unhandledrejection",{cancelable:!0}):(f=t.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return g(f)};b.prototype.X=function(){if(null!=this.g){for(var f=0;f<this.g.length;++f)l.h(this.g[f]);this.g=null}};var l=new c;b.prototype.S=
function(f){var e=this.m();f.D(e.resolve,e.reject)};b.prototype.T=function(f,e){var g=this.m();try{f.call(e,g.resolve,g.reject)}catch(k){g.reject(k)}};b.prototype.then=function(f,e){function g(n,r){return"function"==typeof n?function(V){try{k(n(V))}catch(W){m(W)}}:r}var k,m,q=new b(function(n,r){k=n;m=r});this.D(g(f,k),g(e,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.D=function(f,e){function g(){switch(k.h){case 1:f(k.i);break;case 2:e(k.i);break;default:throw Error("Unexpected state: "+
k.h);}}var k=this;null==this.g?l.h(g):this.g.push(g);this.C=!0};b.resolve=d;b.reject=function(f){return new b(function(e,g){g(f)})};b.race=function(f){return new b(function(e,g){for(var k=w(f),m=k.next();!m.done;m=k.next())d(m.value).D(e,g)})};b.all=function(f){var e=w(f),g=e.next();return g.done?d([]):new b(function(k,m){function q(V){return function(W){n[V]=W;r--;0==r&&k(n)}}var n=[],r=0;do n.push(void 0),r++,d(g.value).D(q(n.length-1),m),g=e.next();while(!g.done)})};return b});
function A(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
u("WeakMap",function(a){function b(g){this.g=(e+=Math.random()+1).toString();if(g){g=w(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}function c(){}function d(g){var k=typeof g;return"object"===k&&null!==g||"function"===k}function h(g){if(!A(g,f)){var k=new c;p(g,f,{value:k})}}function l(g){var k=Object[g];k&&(Object[g]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&h(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),k=Object.seal({}),
m=new a([[g,2],[k,3]]);if(2!=m.get(g)||3!=m.get(k))return!1;m.delete(g);m.set(k,4);return!m.has(g)&&4==m.get(k)}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var e=0;b.prototype.set=function(g,k){if(!d(g))throw Error("Invalid WeakMap key");h(g);if(!A(g,f))throw Error("WeakMap key fail: "+g);g[f][this.g]=k;return this};b.prototype.get=function(g){return d(g)&&A(g,f)?g[f][this.g]:void 0};b.prototype.has=function(g){return d(g)&&A(g,
f)&&A(g[f],this.g)};b.prototype.delete=function(g){return d(g)&&A(g,f)&&A(g[f],this.g)?delete g[f][this.g]:!1};return b});
u("Map",function(a){function b(){var e={};return e.o=e.next=e.head=e}function c(e,g){var k=e.g;return ca(function(){if(k){for(;k.head!=e.g;)k=k.o;for(;k.next!=k.head;)return k=k.next,{done:!1,value:g(k)};k=null}return{done:!0,value:void 0}})}function d(e,g){var k=g&&typeof g;"object"==k||"function"==k?l.has(g)?k=l.get(g):(k=""+ ++f,l.set(g,k)):k="p_"+g;var m=e.h[k];if(m&&A(e.h,k))for(e=0;e<m.length;e++){var q=m[e];if(g!==g&&q.key!==q.key||g===q.key)return{id:k,list:m,index:e,l:q}}return{id:k,list:m,
index:-1,l:void 0}}function h(e){this.h={};this.g=b();this.size=0;if(e){e=w(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),g=new a(w([[e,"s"]]));if("s"!=g.get(e)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var k=g.entries(),m=k.next();if(m.done||m.value[0]!=e||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!k.next().done?!1:!0}catch(q){return!1}}())return a;var l=new WeakMap;h.prototype.set=function(e,g){e=0===e?0:e;var k=d(this,e);k.list||(k.list=this.h[k.id]=[]);k.l?k.l.value=g:(k.l={next:this.g,o:this.g.o,head:this.g,key:e,value:g},k.list.push(k.l),this.g.o.next=k.l,this.g.o=k.l,this.size++);return this};h.prototype.delete=function(e){e=d(this,e);return e.l&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.h[e.id],e.l.o.next=e.l.next,e.l.next.o=e.l.o,e.l.head=null,this.size--,
!0):!1};h.prototype.clear=function(){this.h={};this.g=this.g.o=b();this.size=0};h.prototype.has=function(e){return!!d(this,e).l};h.prototype.get=function(e){return(e=d(this,e).l)&&e.value};h.prototype.entries=function(){return c(this,function(e){return[e.key,e.value]})};h.prototype.keys=function(){return c(this,function(e){return e.key})};h.prototype.values=function(){return c(this,function(e){return e.value})};h.prototype.forEach=function(e,g){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,
e.call(g,m[1],m[0],this)};h.prototype[Symbol.iterator]=h.prototype.entries;var f=0;return h});u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});var B=this||self;function C(a){return a};var ja=Promise;function ka(a){this.h=a}ka.prototype.g=function(a,b,c){this.h.then(function(d){d.g(a,b,c)})};function la(a){this.data=a};function ma(a){this.h=a}ma.prototype.g=function(a,b,c){c=void 0===c?[]:c;var d=new MessageChannel;na(d.port1,b);this.h.postMessage(a,[d.port2].concat(c))};function oa(a,b){na(a,b);return new ma(a)}function na(a,b){b&&(a.onmessage=function(c){b(new la(c.data,oa(c.ports[0])))})};function pa(a){var b=a.H,c=void 0===a.A?"ZNWN1d":a.A,d=void 0===a.onMessage?void 0:a.onMessage,h=void 0===a.F?void 0:a.F;return qa({destination:a.destination,U:function(){return b.contentWindow},V:ra(a.origin),A:c,onMessage:d,F:h})}
function qa(a){var b=a.destination,c=a.U,d=a.V,h=void 0===a.W?void 0:a.W,l=a.A,f=void 0===a.onMessage?void 0:a.onMessage,e=void 0===a.F?void 0:a.F,g=Object.create(null);d.forEach(function(k){g[k]=!0});return new ka(new ja(function(k,m){function q(n){if(n.source===c())if(!0!==g[n.origin]){b.removeEventListener("message",q,!1);var r=d.join(", ");m(Error("Origin mismatch while establishing channel. Expected "+(1===d.length?r:"one of ["+r+"]")+", but received "+n.origin+"."))}else(n.data.n||n.data)===
l&&(b.removeEventListener("message",q,!1),h&&n.data.t!==h?m(Error("Token mismatch while establishing channel. Expected "+h+", but received "+n.data.t+".")):(k(oa(n.ports[0],f)),e&&e(n)))}b.addEventListener("message",q,!1)}))}function ra(a){a="string"===typeof a?[a]:a;var b=Object.create(null);a.forEach(function(c){if("null"===c)throw Error("Receiving from null origin not allowed without token verification. Please use NullOriginConnector.");b[c]=!0});return a};var sa={},D=null;
function ta(a){var b;void 0===b&&(b=0);if(!D){D={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],h=0;5>h;h++){var l=c.concat(d[h].split(""));sa[h]=l;for(var f=0;f<l.length;f++){var e=l[f];void 0===D[e]&&(D[e]=f)}}}b=sa[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(h=l=0;l<a.length-2;l+=3){var g=a[l],k=a[l+1];e=a[l+2];f=b[g>>2];g=b[(g&3)<<4|k>>4];k=b[(k&15)<<2|e>>6];e=b[e&63];c[h++]=f+g+k+e}f=0;e=d;switch(a.length-l){case 2:f=
a[l+1],e=b[(f&15)<<2]||d;case 1:a=a[l],c[h]=b[a>>2]+b[(a&3)<<4|f>>4]+e+d}return c.join("")};var E="undefined"!==typeof Uint8Array,ua={};var va;function F(a){if(ua!==ua)throw Error("illegal external caller");this.N=a;if(null!==a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");};var wa={};var G="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function H(a,b){Object.isFrozen(a)||(G?a[G]|=b:void 0!==a.v?a.v|=b:Object.defineProperties(a,{v:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function xa(a){var b;G?b=a[G]:b=a.v;return null==b?0:b}function I(a){H(a,1);return a}function J(a){return Array.isArray(a)?!!(xa(a)&2):!1}function ya(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");H(a,2)};function za(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Aa,Ba=Object.freeze(I([]));function K(a){if(J(a.j))throw Error("Cannot mutate an immutable Message");}var Ca="undefined"!=typeof Symbol&&"undefined"!=typeof Symbol.hasInstance;function Da(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function Ea(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(E&&null!=a&&a instanceof Uint8Array)return ta(a);if(a instanceof F){var b=a.N;b=null==b||"string"===typeof b?b:E&&b instanceof Uint8Array?ta(b):null;return(a.N=b)||""}}}return a};function Fa(a){var b=Ga;b=void 0===b?Ha:b;return Ia(a,b)}function Ja(a,b){if(null!=a){if(Array.isArray(a))a=Ia(a,b);else if(za(a)){var c={},d;for(d in a)c[d]=Ja(a[d],b);a=c}else a=b(a);return a}}function Ia(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=Ja(c[d],b);Array.isArray(a)&&xa(a)&1&&I(c);return c}function Ga(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=Ea(a);return Array.isArray(a)?Fa(a):a}function Ha(a){return E&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};function Ka(a){return a.h||(a.h=a.j[a.i+a.u]={})}function La(a,b,c){return-1===b?null:b>=a.i?a.h?a.h[b]:void 0:(void 0===c?0:c)&&a.h&&(c=a.h[b],null!=c)?c:a.j[b+a.u]}function L(a,b,c,d,h){d=void 0===d?!1:d;(void 0===h?0:h)||K(a);b<a.i&&!d?a.j[b+a.u]=c:Ka(a)[b]=c}function Ma(a,b){for(var c=0,d=0;d<b.length;d++){var h=b[d];null!=La(a,h)&&(0!==c&&L(a,c,void 0,!1,!0),c=h)}return c}
function Na(a,b,c){K(a);a.g||(a.g={});var d=null!=c?c.j:c;a.g[1]=c;K(a);(b=Ma(a,b))&&1!==b&&null!=d&&(a.g&&b in a.g&&(a.g[b]=void 0),L(a,b));L(a,1,d)};function M(a,b,c){a||(a=N);N=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.u=(d?0:-1)-(this.constructor.g||0);this.g=void 0;this.j=a;a:{d=this.j.length;a=d-1;if(d&&(d=this.j[a],za(d))){this.i=a-this.u;this.h=d;break a}void 0!==b&&-1<b?(this.i=Math.max(b,a+1-this.u),this.h=void 0):this.i=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.i)a+=this.u,(d=this.j[a])?Array.isArray(d)&&I(d):this.j[a]=Ba;else{d=Ka(this);var h=d[a];h?Array.isArray(h)&&I(h):d[a]=Ba}}
M.prototype.toJSON=function(){var a=this.j;return Aa?a:Fa(a)};function Oa(a){Aa=!0;try{return JSON.stringify(a.toJSON(),Pa)}finally{Aa=!1}}function O(a,b){if(null==b||""==b)return new a;b=JSON.parse(b);if(!Array.isArray(b))throw a=typeof b,Error("Expected to deserialize an Array but got "+("object"!=a?a:b?Array.isArray(b)?"array":a:"null")+": "+b);N=b;a=new a(b);N=null;return a}M.prototype.toString=function(){return this.j.toString()};function Pa(a,b){return Ea(b)}var N;function P(){M.apply(this,arguments)}z(P,M);P.prototype.M=function(){return this};if(Ca){var Qa={};Object.defineProperties(P,(Qa[Symbol.hasInstance]=Da(function(){throw Error("Cannot perform instanceof checks for MutableMessage");}),Qa))};function Ra(a,b,c,d,h,l){if(a=a.g&&a.g[c])if(Array.isArray(a)){d=l.G?I(a.slice()):a;K(b);if(null!=d){h=I([]);l=!1;for(a=0;a<d.length;a++)h[a]=d[a].j,l=l||J(h[a]);b.g||(b.g={});b.g[c]=d;d=h;if(!Array.isArray(d))throw Error("cannot mark non-array as mutable");l?Object.isFrozen(d)||(G?d[G]&=-9:void 0!==d.v&&(d.v&=-9)):H(d,8)}else b.g&&(b.g[c]=void 0),h=Ba;L(b,c,h)}else K(b),b.g||(b.g={}),h=null!=a?a.j:a,b.g[c]=a,L(b,c,h);else E&&d instanceof Uint8Array?h=d.length?new F(new Uint8Array(d)):va||(va=new F(null)):
(Array.isArray(d)&&(h?ya(d):Array.isArray(d)&&xa(d)&1&&l.G&&(d=d.slice())),h=d),L(b,c,h)};function Q(){P.apply(this,arguments)}z(Q,P);
Q.prototype.M=function(a){if(a!==wa)throw Error("requires a valid immutable API token");if(J(this.j)){a={G:!0};var b=J(this.j);if(b&&!a.G)throw Error("copyRepeatedFields must be true for frozen messages");var c=new this.constructor;this.I&&(c.I=this.I.slice());for(var d=this.j,h=0;h<d.length;h++){var l=d[h];if(h===d.length-1&&za(l))for(e in l){var f=+e;Number.isNaN(f)?Ka(c)[e]=l[e]:Ra(this,c,f,l[e],b,a)}else Ra(this,c,h-this.u,l,b,a)}var e=c}else e=this;return e};
if(Ca){var Sa={};Object.defineProperties(Q,(Sa[Symbol.hasInstance]=Da(Object[Symbol.hasInstance]),Sa))};var Ta=void 0;function R(a,b){var c=Ta;Ta=void 0;if(!b(a))throw b=c?c()+"\n":"",Error(b+String(a));};function Ua(a){return"string"===typeof a}function S(a){return"function"===typeof a};var T;function U(a,b){this.g=b===Va?a:""}U.prototype.toString=function(){return this.g+""};U.prototype.i=!0;U.prototype.h=function(){return this.g.toString()};function Wa(a){return a instanceof U&&a.constructor===U?a.g:"type_error:TrustedResourceUrl"}var Va={};
function Xa(a){if(void 0===T){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:C,createScript:C,createScriptURL:C})}catch(d){B.console&&B.console.error(d.message)}T=b}else T=b}a=(b=T)?b.createScriptURL(a):a;return new U(a,Va)};function X(a,b){this.g=b===Ya?a:""}X.prototype.toString=function(){return this.g.toString()};X.prototype.i=!0;X.prototype.h=function(){return this.g.toString()};var Za=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Ya={};/*

 SPDX-License-Identifier: Apache-2.0
*/
function $a(a){var b=ia.apply(1,arguments);if(0===b.length)return Xa(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return Xa(c.join(""))}function ab(a,b){var c=Wa(a).toString();if(/#/.test(c))throw Error("");var d=/\?/.test(c)?"&":"?";b.forEach(function(h,l){h=h instanceof Array?h:[h];for(var f=0;f<h.length;f++){var e=h[f];null!==e&&void 0!==e&&(c+=d+encodeURIComponent(l)+"="+encodeURIComponent(String(e)),d="&")}});return Xa(c)};function bb(a){return!!a&&"function"===typeof a.openConsoleTab&&"function"===typeof a.attachOverlay};function cb(a){Q.call(this,a)}z(cb,Q);function db(a){Q.call(this,a)}z(db,Q);function eb(a){Q.call(this,a)}z(eb,Q);var fb=[1];function gb(a){Q.call(this,a)}z(gb,Q);function hb(a){Q.call(this,a)}z(hb,Q);var ib=[1];function jb(a){Q.call(this,a)}z(jb,Q);var kb=[1];function lb(a){Q.call(this,a)}z(lb,Q);function mb(a){return a instanceof Element}function nb(){var a=ob.h;this.h=ob.g;this.g=a}nb.prototype.openConsoleTab=function(a,b,c){R(a,Ua);R(b,S);R(c,S);a=O(gb,a);var d=new MessageChannel,h=d.port1;d=d.port2;h.onmessage=function(l){"ACK"===l.data?c(h):b(l.data)};this.h.openConsoleTab(a,d)};
nb.prototype.attachOverlay=function(a,b,c,d){R(a,Ua);R(b,mb);R(c,S);R(d,S);a=O(cb,a);var h=new MessageChannel,l=h.port1;h=h.port2;l.onmessage=function(f){"ACK"===f.data?d(l):c(f.data)};this.g.attachOverlay(a,b,h)};var pb=window.URL,Y=B.document.baseURI||B.window.location.href||"",qb;try{new pb("http://example.com"),qb=!0}catch(a){qb=!1}var rb=qb;
function Z(a){var b=document;var c="A";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);try{var d=new X(a,Ya);if(d instanceof X)var h=d;else d instanceof X?h=d:(d="object"==typeof d&&d.i?d.h():String(d),Za.test(d)||(d="about:invalid#zClosurez"),h=new X(d,Ya));var l=h;c.href=l instanceof X&&l.constructor===X?l.g:"type_error:SafeUrl";var f=c.protocol}catch(e){throw Error(a+" is not a valid URL.");}if(""===f||":"===f||":"!=f[f.length-1])throw Error(a+" is not a valid URL.");
if(!sb.has(f))throw Error(a+" is not a valid URL.");if(!c.hostname)throw Error(a+" is not a valid URL.");a={href:c.href,protocol:c.protocol,username:"",password:"",hostname:c.hostname,pathname:"/"+c.pathname,search:c.search,hash:c.hash};sb.get(c.protocol)===c.port?(a.host=a.hostname,a.port="",a.origin=a.protocol+"//"+a.hostname):(a.host=c.host,a.port=c.port,a.origin=a.protocol+"//"+a.hostname+":"+a.port);return a}
function tb(a){try{var b=new pb(a)}catch(d){throw Error(a+" is not a valid URL.");}var c=sb.get(b.protocol);if(!c)throw Error(a+" is not a valid URL.");if(!b.hostname)throw Error(a+" is not a valid URL.");if("null"!=b.origin)return b;a={href:b.href,protocol:b.protocol,username:"",password:"",host:b.host,port:b.port,hostname:b.hostname,pathname:b.pathname,search:b.search,hash:b.hash};a.origin=c===b.port?b.protocol+"//"+b.hostname:b.protocol+"//"+b.hostname+":"+b.port;return a}
function ub(a){if(rb){if(!Y)return tb(a);var b=tb(Y);try{return tb(a)}catch(h){}return new pb(a,b.href)}if(!Y)return Z(a);b=Z(Y);try{return Z(a)}catch(h){}var c=b.username,d=b.password;c=b.protocol+"//"+(c&&d?c+":"+d+"@":c?c+"@":d?":"+d+"@":"")+b.host;d=a[0];"/"===d||"\\"===d?a=c+a:"?"===d?a=c+b.pathname+a:d&&"#"!==d?(d=b.pathname.lastIndexOf("/"),a=c+(0<d?b.pathname.substring(0,d):"")+"/"+a):a=c+b.pathname+b.search+a;return Z(a)}
var sb=new Map([["http:","80"],["https:","443"],["ws:","80"],["wss:","443"],["ftp:","21"]]);function vb(){this.g=wb;this.h=0}
vb.prototype.attachOverlay=function(a,b,c,d){var h=this.h++,l=document.createElement("div");l.id="gatc:overlay:div:"+h;l.classList.add("gatc:overlay:div");l.style.position="absolute";l.style.top="0";l.style.left="0";l.style.bottom="0";l.style.right="0";l.style.border="none";b.appendChild(l);var f=document.createElement("iframe");f.id="gatc:overlay:frame:"+h;f.classList.add("gatc:overlay:frame");f.style.width="100%";f.style.height="100%";f.style.border="none";b=pa({destination:window,H:f,origin:ub(this.g.J.toString()).origin,
A:"gatc:overlay:channel:"+h,onMessage:function(e){e.data&&(e=O(lb,e.data.data||""),console.log("Received overlay message: ",e.toString(),h))}});d&&d(f);d=ab(this.g.J,new Map([["origin",window.origin],["index",h.toString()]]));f.src=Wa(d).toString();l.appendChild(f);l=new jb;Na(l,kb,a);a={data:Oa(l),ports:[c]};b.g(a,void 0,a.ports)};function xb(){var a=wb;var b=void 0===b?document.body:b;this.s=a;this.B=b;this.m=!1}xb.prototype.install=function(a){if(this.m)throw Error("Panel manager may only be installed once.");this.m=!0;yb(this,a)};xb.prototype.openConsoleTab=function(a,b){if(!this.m)throw Error("Panel manager must be installed before access.");var c=new hb;Na(c,ib,a);a={data:Oa(c),ports:[b]};this.C.g(a,void 0,a.ports)};
function yb(a,b){if(document.getElementById("gatc:panel:div")||document.getElementById("gatc:panel:frame")||document.getElementById("gatc:panel:scrollshim"))throw Error("Panel elements already present in document.");a.g=document.createElement("div");a.g.id="gatc:panel:div";a.g.style.position="fixed";a.g.style.bottom="0";a.g.style.left="0";a.g.style.right="0";a.g.style.height="330px";a.g.style.borderTop="1px solid #ccc";a.g.style.background="white";a.g.style.overflow="hidden";a.g.style.zIndex="2147483646";
a.g.style.display="none";a.B.appendChild(a.g);a.h=document.createElement("div");a.h.id="gatc:panel:scrollshim";a.h.style.width="100%";a.h.style.height="330px";a.h.style.clear="both";a.h.style.display="none";a.B.appendChild(a.h);a.i=document.createElement("iframe");a.i.id="gatc:panel:frame";a.i.style.width="100%";a.i.style.height="100%";b&&b(a.i);a.C=pa({destination:window,H:a.i,origin:ub(a.s.K.toString()).origin,A:"gatc:panel:channel",onMessage:function(c){if(c.data&&(c=O(eb,c.data.data||""),1===
Ma(c,fb))){var d=1===Ma(c,fb)?1:-1;var h=void 0===h?!1:h;if(-1===d)var l=null;else if(c.g||(c.g={}),l=c.g[d],!l){var f=La(c,d,h);var e=void 0;e=void 0===e?!1:e;f=Array.isArray(f)?new db(f):e?new db:void 0;void 0!=f&&(c.g[d]=f,J(c.j)&&ya(f.j),l=f)}null!=l&&J(l.j)&&!J(c.j)&&(l=l.M(wa),L(c,d,l.j,h),c.g[d]=l);if(!a.g)throw Error("Panel manager must be installed before access.");h=La(l,1);switch(null==h?0:h){case 1:zb(a,"none");break;case 2:zb(a,"")}}}});a.C.g(null,function(){});b=ab(a.s.K,new Map([["origin",
window.origin]]));a.i.src=Wa(b).toString();a.g.appendChild(a.i)}function zb(a,b){a.g&&(a.g.style.display=b);a.h&&(a.h.style.display=b)};var Ab=v(["https://www.googletagservices.com/console/host/host.js"]),Bb=v(["https://www.googletagservices.com/console/panel/index.php"]),Cb=v(["https://www.googletagservices.com/console/overlay/index.php"]),wb={Z:$a(Ab),K:$a(Bb),J:$a(Cb)};var ob=new function(){var a=new vb;this.g=new xb;this.h=a};if(bb(window.gatc_host))throw Error("Host module already installed on window.");ob.g.install();var Db=new nb;R(Db,bb);if(Array.isArray(window.gatc_host))for(var Eb=w(window.gatc_host),Fb=Eb.next();!Fb.done;Fb=Eb.next()){var Gb=Fb.value;"function"===typeof Gb&&Gb(Db)}window.gatc_host=Db;}).call(this);
